fix(index.ts): modified default server port in index.ts and webpack.dev.js
oslabs-beta/infernode pull request #225
Opened 2022-09-30 13:04 UTC by cdschexnide

I updated the port number in index.ts to avoid conflicts with the use of port 3000. I also changed the webpack proxy target to match the change.

'fix #207'

2022-09-30 15:56 UTC, 8000meters requested changes
Looks great Cody! just needs to pass the build tests before it can be merged.

2022-10-01 00:47 UTC, seadubs commented
Looks like things are passing after #226 merged

2022-10-06 18:56 UTC, 8000meters approved these changes

2022-10-21 16:00 UTC, 8000meters commented
this will probably need to be updated again since its out of date with dev branch now

2022-10-21 17:21 UTC, merged