Feature/histroy page display svg component
oslabs-beta/infernode pull request #48
Opened 2022-08-22 15:14 UTC by hmu1540

1. Utilize SVGR loader to load svg file from the filesystem
2. Create svg react component

2022-08-22 15:38 UTC, 8000meters requested changes
nvm

2022-08-22 15:40 UTC, 8000meters commented
Also looks like the json files need to be updated since the tests failed.

2022-08-23 17:48 UTC, dzidupe approved these changes
Looks good

2022-08-23 18:45 UTC, 8000meters approved these changes

2022-08-23 18:47 UTC, merged